[toolchain]

[features]
resolution = true
skip-lint = false

[programs.testnet]
memo_mint = "TD8dwXKKg7M3QpWa9mQQpcvzaRasDU1MjmQWqZ9UZiw"
memo_burn = "FEjJ9KKJETocmaStfsFteFrktPchDLAVNTMeTvndoxaP"

# [programs.mainnet]


[registry]
url = "https://api.apr.dev"

[provider]
# testnet
cluster = "https://rpc-testnet.x1.wiki"
wallet = "~/.config/solana/id.json"
