[toolchain]

[features]
resolution = true
skip-lint = false

[programs.testnet]
memo_mint = "A31a17bhgQyRQygeZa1SybytjbCdjMpu6oPr9M3iQWzy"
memo_burn = "FEjJ9KKJETocmaStfsFteFrktPchDLAVNTMeTvndoxaP"
memo_chat = "54ky4LNnRsbYioDSBKNrc5hG8HoDyZ6yhf8TuncxTBRF"
memo_profile = "BwQTxuShrwJR15U6Utdfmfr4kZ18VT6FA1fcp58sT8US"
memo_project = "ENVapgjzzMjbRhLJ279yNsSgaQtDYYVgWq98j54yYnyx"

# [programs.mainnet]


[registry]
url = "https://api.apr.dev"

[provider]
# testnet
cluster = "https://rpc.testnet.x1.xyz"
wallet = "~/.config/solana/id.json"
