[toolchain]

[features]
resolution = true
skip-lint = false

[programs.testnet]
memo_mint = "A31a17bhgQyRQygeZa1SybytjbCdjMpu6oPr9M3iQWzy"
memo_burn = "FEjJ9KKJETocmaStfsFteFrktPchDLAVNTMeTvndoxaP"

# [programs.mainnet]


[registry]
url = "https://api.apr.dev"

[provider]
# testnet
cluster = "https://rpc-testnet.x1.wiki"
wallet = "~/.config/solana/id.json"
